language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.6-dev"

addons:
  apt:
    packages:
      - git

before_script:
  - sudo pip install flake8

script:
  - flake8
  - python -m unittest discover
